mysite/BlogApp/urls.py
from django.urls import path

from BlogApp.views import ArticleListView, ArticleDetailView, LatestArticlesFeed

app_name = 'blogapp'

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('articles/<int:pk>/', ArticleDetailView.as_view(), name='article'),
    path('articles/latest/feed/', LatestArticlesFeed(), name='articles-feed'),
    ]

mysite/mainpage/urls.py
from django.urls import path
from .views import MainpageView

app_name = 'mainpage'

urlpatterns = [
    path('', MainpageView.as_view(), name='index'),

]

mysite/myapiapp/urls.py
from django.urls import path

from .views import hello_world_view, GroupsListView

app_name = "myapiapp"


urlpatterns = [
    path("hello/", hello_world_view, name='hello'),
    path("groups/", GroupsListView.as_view(), name="groups"),
]

mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

# from .views import login_view, logout_view
from myauth.views import get_cookie_view, set_cookie_view, set_session_view, get_session_view, MyLogoutView, \
    AboutMeView, RegisterView, FooBarView, ChangeAvatarView, ProfileListView, ProfileDetailsView, \
    ChangeAvatarIsStaffView, HelloView

app_name = 'myauth'

urlpatterns = [
    path('login/',
         LoginView.as_view(
             template_name='myauth/login.html',
             redirect_authenticated_user=True),
         name='login'),
    path('hello/', HelloView.as_view(), name='hello'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('cookie/get/', get_cookie_view, name='cookie-get'),
    path('cookie/set/', set_cookie_view, name='cookie-set'),
    path('session/get/', get_session_view, name='session-get'),
    path('session/set/', set_session_view, name='session-set'),

    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path('register/', RegisterView.as_view(), name='register'),
    path('change-avatar/<int:pk>/', ChangeAvatarView.as_view(), name='change-avatar'),

    path("profiles-list/", ProfileListView.as_view(), name="profiles-list"),
    path("profiles-details/<int:pk>/", ProfileDetailsView.as_view(), name="profile-details"),
    path('profiles-details/<int:pk>/change-avatar-staff', ChangeAvatarIsStaffView.as_view(),
         name='change-avatar-staff'),

    path('foo-bar/', FooBarView.as_view(), name='foo-bar')
    # path('login/', login_view, name='login'),
    # path('logout/', logout_view, name='logout'),

]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from .sitemaps import sitemaps

urlpatterns = []

urlpatterns += i18n_patterns(
    path('', include('mainpage.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('shop/', include('shopapp.urls')),
    path('accounts/', include('myauth.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swager/', SpectacularSwaggerView.as_view(url_name='schema'), name='swager'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('blog/', include('BlogApp.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    )

)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/requestdataapp/urls.py
from django.urls import path
from .views import process_get_view, user_form, handle_file_upload

app_name = 'requestdataapp'

urlpatterns = [
    path('get/', process_get_view, name='get-view'),
    path('bio/', user_form, name='user-form'),
    path('upload/', handle_file_upload, name='file-upload'),
]

mysite/shopapp/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter

from .views import ShopIndexView, GroupListView, ProductDetailsView, ProductsListView, OrdersListView, \
    OrdersDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, OrderCreateView, OrderUpdateView, \
    OrderDeleteView, ProductsDataExportView, OrderDataExportView, ProductViewSet, OrderViewSet, LatestProductsFeed, \
    UserOrdersListView, UserOrdersDataExportView


app_name = 'shopapp'

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)


urlpatterns = [
    path('', ShopIndexView.as_view(), name='index'),
    path('api', include(routers.urls)),
    path('groups/', GroupListView.as_view(), name='groups_list'),
    path('products/', ProductsListView.as_view(), name='products_list'),
    path('products/export', ProductsDataExportView.as_view(), name='products-export'),
    path('products/create', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/<int:pk>/update', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/archive', ProductDeleteView.as_view(), name='product_delete'),
    path('products/latest/feed/', LatestProductsFeed(), name='products-feed'),

    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/export', OrderDataExportView.as_view(), name='orders-export'),
    path('orders/create/', OrderCreateView.as_view(), name='order_create'),
    path('orders/<int:pk>/', OrdersDetailView.as_view(), name='order_details'),
    path('orders/<int:pk>/update', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/confirm-delete', OrderDeleteView.as_view(), name='order_confirm_delete'),

    path('users/<int:pk>/orders', UserOrdersListView.as_view(), name='user_orders_list'),
    path('users/<int:pk>/orders/export', UserOrdersDataExportView.as_view(), name='user_orders_list_export'),

]

mysite/mainpage/models.py
from django.db import models

# Create your models here.

mysite/mainpage/views.py
from timeit import default_timer

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views import View


class MainpageView(View):
    def get(self, request: HttpRequest) -> HttpResponse:

        context = {
            "time_running": default_timer(),
        }
        return render(request, 'mainpage/index.html', context=context)

mysite/mainpage/templates/mainpage/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>
        {% block title %}
            Main Page
        {% endblock %}
    </title>
</head>
<header>
    {% include 'mainpage/nav-bar.html' %}
</header>
<body>


{% block index-body %}
    <div align="center"><h1>Welcome to my site</h1></div>
{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

mysite/mainpage/templates/mainpage/nav-bar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'mainpage:index' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shopapp:index' %}">Shop</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Request Data App
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'requestdataapp:user-form' %}">Bio</a>
                    <a class="dropdown-item" href="{% url 'requestdataapp:file-upload' %}">Upload</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    EndPoints
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'shopapp:index' %}">Shop Index</a>
                    <a class="dropdown-item" href="{% url 'shopapp:products_list' %}">Product list</a>
                    <a class="dropdown-item" href="{% url 'shopapp:product_create' %}">Product Create</a>
                    <a class="dropdown-item" href="{% url 'shopapp:orders_list' %}">Order list</a>
                    <a class="dropdown-item" href="{% url 'shopapp:order_create' %}">Order create </a>
                    <a class="dropdown-item" href="{% url 'requestdataapp:user-form' %}">Bio</a>
                    <a class="dropdown-item" href="{% url 'requestdataapp:file-upload' %}">Upload</a>
                    <a class="dropdown-item" href="{% url 'myauth:login' %}">LogIn</a>
                    <a class="dropdown-item" href="{% url 'myauth:logout' %}">LogOut</a>
                    <a class="dropdown-item" href="{% url 'myauth:about-me' %}">About me</a>
                    <a class="dropdown-item" href="{% url 'blogapp:articles' %}">Blog App</a>
                    <a class="dropdown-item" href="{% url 'myauth:cookie-get' %}">Cookie Get</a>
                    <a class="dropdown-item" href="{% url 'myauth:cookie-set' %}">Cookie Set</a>
                    <a class="dropdown-item" href="{% url 'myauth:session-get' %}">Session Get</a>
                    <a class="dropdown-item" href="{% url 'myauth:session-set' %}">Session Set</a>
                    <a class="dropdown-item" href="{% url 'myauth:register' %}">Register</a>
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                    <a class="dropdown-item" href="{% url 'myauth:profiles-list' %}">Profile List</a>
                    <a class="dropdown-item" href="{% url 'myapiapp:hello' %}">API Hello</a>
                    <a class="dropdown-item" href="{% url 'shopapp:api-root' %}">API Product/Order</a>
                </div>
            </li>
        </ul>
    </div>
</nav>