mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

# from .views import login_view, logout_view
from myauth.views import get_cookie_view, set_cookie_view, set_session_view, get_session_view, MyLogoutView, \
    AboutMeView, RegisterView, FooBarView, ChangeAvatarView, ProfileListView, ProfileDetailsView, \
    ChangeAvatarIsStaffView, HelloView

app_name = 'myauth'

urlpatterns = [
    path('login/',
         LoginView.as_view(
             template_name='myauth/login.html',
             redirect_authenticated_user=True),
         name='login'),
    path('hello/', HelloView.as_view(), name='hello'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('cookie/get/', get_cookie_view, name='cookie-get'),
    path('cookie/set/', set_cookie_view, name='cookie-set'),
    path('session/get/', get_session_view, name='session-get'),
    path('session/set/', set_session_view, name='session-set'),

    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path('register/', RegisterView.as_view(), name='register'),
    path('change-avatar/<int:pk>/', ChangeAvatarView.as_view(), name='change-avatar'),

    path("profiles-list/", ProfileListView.as_view(), name="profiles-list"),
    path("profiles-details/<int:pk>/", ProfileDetailsView.as_view(), name="profile-details"),
    path('profiles-details/<int:pk>/change-avatar-staff', ChangeAvatarIsStaffView.as_view(),
         name='change-avatar-staff'),

    path('foo-bar/', FooBarView.as_view(), name='foo-bar')
    # path('login/', login_view, name='login'),
    # path('logout/', logout_view, name='logout'),

]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from .sitemaps import sitemaps

urlpatterns = []

urlpatterns += i18n_patterns(
    path('', include('mainpage.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('shop/', include('shopapp.urls')),
    path('accounts/', include('myauth.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swager/', SpectacularSwaggerView.as_view(url_name='schema'), name='swager'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('blog/', include('BlogApp.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    )

)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/shopapp/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter

from .views import ShopIndexView, GroupListView, ProductDetailsView, ProductsListView, OrdersListView, \
    OrdersDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, OrderCreateView, OrderUpdateView, \
    OrderDeleteView, ProductsDataExportView, OrderDataExportView, ProductViewSet, OrderViewSet, LatestProductsFeed, \
    UserOrdersListView, UserOrdersDataExportView


app_name = 'shopapp'

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)


urlpatterns = [
    path('', ShopIndexView.as_view(), name='index'),
    path('api', include(routers.urls)),
    path('groups/', GroupListView.as_view(), name='groups_list'),
    path('products/', ProductsListView.as_view(), name='products_list'),
    path('products/export', ProductsDataExportView.as_view(), name='products-export'),
    path('products/create', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/<int:pk>/update', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/archive', ProductDeleteView.as_view(), name='product_delete'),
    path('products/latest/feed/', LatestProductsFeed(), name='products-feed'),

    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/export', OrderDataExportView.as_view(), name='orders-export'),
    path('orders/create/', OrderCreateView.as_view(), name='order_create'),
    path('orders/<int:pk>/', OrdersDetailView.as_view(), name='order_details'),
    path('orders/<int:pk>/update', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/confirm-delete', OrderDeleteView.as_view(), name='order_confirm_delete'),

    path('users/<int:pk>/orders', UserOrdersListView.as_view(), name='user_orders_list'),
    path('users/<int:pk>/orders/export', UserOrdersDataExportView.as_view(), name='user_orders_list_export'),

]

mysite/shopapp/views.py
import logging
import os
from csv import DictWriter

from timeit import default_timer

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import Group, User
from django.contrib.syndication.views import Feed
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.shortcuts import render, redirect, reverse
from django.core.cache import cache
from django.template.response import SimpleTemplateResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.decorators import action
from rest_framework.parsers import MultiPartParser
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, OpenApiResponse

from .common import save_csv_products
from shopapp.models import Product, Order, ProductImage
from .forms import GroupForm, ProductIMGForm
from .serializers import ProductSerializer, OrderSerializer

# log = logging.getLogger(__name__)
log = logging.getLogger("info_log")


@extend_schema(description='Product Views CRUD')
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product.
    Полный CRUD для сущностей товара.
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["name", "description"]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived",
    ]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]

    @extend_schema(
        summary='Get one product by ID',
        description='Retrieves **product**, returns 404 if not found',
        responses={
            200: ProductSerializer,
            400: OpenApiResponse(description='Empty response, product by id not found'),
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        filename = "products-export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "name",
            "description",
            "price",
            "discount",
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })
        return response

    @action(
        detail=False,
        methods=["post"],
        parser_classes=[MultiPartParser],
    )
    def upload_csv(self, request: Request) -> Response:
        products = save_csv_products(
            request.FILES["file"].file,
            encoding=request.encoding,
            user=request.user,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)

    @method_decorator(cache_page(60 * 1))
    def list(self, *args, **kwargs):
        return super().list(*args, **kwargs)


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["name", "description"]
    filterset_fields = [
        "delivery_address",
        "promo_code",
        "user",
        "products",
    ]
    ordering_fields = [
        "delivery_address",
        "promo_code",
        "created_at",
    ]

    def perform_create(self, serializer):
        print('printing user: ', self.request.user)
        serializer.save(user=self.request.user)

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        filename = "orders-export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "delivery_address",
            "promo_code",
            "created_at",
            "products",
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for order in queryset:
            writer.writerow({
                field: getattr(order, field)
                for field in fields
            })
        return response


class ShopIndexView(View):

    # @method_decorator(cache_page(60 * 1))
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('laptop', 1999),
            ('desktop', 2999),
            ('smartphone', 999),
        ]
        context = {
            "time_running": default_timer(),
            "products": products,
            'items': 5,
        }
        # logger_info.debug("Products for shop index: %s ", products)
        log.info("Rendering shop index")
        print('shop index context ', context)
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related("permissions").all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(request.path)


class ProductsListView(ListView):
    """ Product 1"""
    template_name = 'shopapp/products-list.html'
    context_object_name = "products"
    queryset = Product.objects.filter(archived=False)


class ProductDetailsView(DetailView):
    """ Product 2"""
    template_name = 'shopapp/product-details.html'
    model = Product
    context_object_name = "product"


class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'shopapp.add_product'
    model = Product
    # fields = "name", "price", "description", "discount", 'preview'
    success_url = reverse_lazy("shopapp:products_list")
    form_class = ProductIMGForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        response = super().form_valid(form)

        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )
        return response


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        if self.request.user.is_superuser:
            return True
        return self.request.user.has_perm('shopapp.change_product') \
               and self.get_object().created_by == self.request.user

    model = Product
    # fields = "name", "price", "description", "discount", 'preview'
    template_name_suffix = '_update_form'
    form_class = ProductIMGForm

    def get_success_url(self):
        return reverse(
            'shopapp:product_details',
            kwargs={"pk": self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )
        return response


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects.select_related('user').prefetch_related('products')
    )


class OrdersDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'shopapp.view_order'
    queryset = (
        Order.objects.select_related('user').prefetch_related('products')
    )


class OrderCreateView(CreateView):
    model = Order
    fields = "delivery_address", "promo_code", "products"
    success_url = reverse_lazy("shopapp:orders_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        response = super().form_valid(form)
        return response


class OrderUpdateView(UpdateView):
    model = Order
    fields = "delivery_address", "promo_code", "user", "products"
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'shopapp:order_details',
            kwargs={"pk": self.object.pk},
        )


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('shopapp:orders_list')


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        cache_key = "products_data_export"
        products_data = cache.get(cache_key)
        if products_data is None:
            products = Product.objects.order_by('pk').all()
            products_data = [
                {
                    'pk': product.pk,
                    'name': product.name,

mysite/shopapp/templates/shopapp/404.html.html
{% extends 'shopapp/base.html' %}

{% block title %}
No User #
{% endblock %}

{% block body %}
<h1>404 Error</h1>
    <h3>No such User exists in DB</h3>
{% endblock %}

mysite/shopapp/templates/shopapp/base.html
{% extends 'mainpage/index.html' %}

{% block index-body %}

    {% block body %}

    {% endblock %}

    <div>
        {% now 'H:i' %}
    </div>
    <div>
        {% now 'l' as current_week_day %}
        Today is {{ current_week_day }}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Group List
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        {% if groups %}
            <ul>
                {% for group in groups %}
                    <li>
                        <div>{{ group.name }} </div>
                        <ul>
                            {% for permission in group.permissions.all %}
                                <li>
                                    {{ permission.name }}
                                    <code>{{ permission.codename }}</code>
                                </li>
                            {% endfor %}

                        </ul>
                    </li>
                {% endfor %}

            </ul>
        {% else %}
            <h3>No groups yet</h3>
        {% endif %}
    </div>
    <br><br>
    <div>
        <a href="{% url 'shopapp:product_create' %}"> Create product</a>
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:index' %}"> Go back to shop-index</a>
    </div>
    <br>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm Delete order #{{ object.pk }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to Delete order #{{ object.pk }}?</h1>

    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order</a>
    </div>
    <br>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if object_list %}
        <div>
            {% for order in object_list %}
                <div>
                <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Details #{{ order.pk }}</a></p>
                    <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                    <p>Promo code:
                        <code>{{ order.promo_code }}</code>
                    </p>
                    <p>Delivery address: {{ order.delivery_address }}</p>
                    <div>
                        Products in order:
                        <ul>
                            {% for product in order.products.all %}
                                <li>{{ product.name }} for ${{ product.price }}</li>
                            {% endfor %}
                        </ul>
                    </div>

                </div>
            {% endfor %}
        </div>

    {% else %}
        <h3>No orders yet</h3>
    {% endif %}
    <br><br>

    <div>
        <a href="{% url 'shopapp:order_create' %}">Create order</a>
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:index' %}"> Go back to shop-index</a>
    </div>
    <br>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update order #{{ object.pk }}
{% endblock %}

{% block body %}
    <h1>Update new order:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <br><br>
    <di>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order #{{ object.pk }}</a>
    </di>
    <br><br>

{% endblock %}

mysite/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% translate 'Product' %} #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>{% translate 'Product' %} <strong>{{ product.name }}</strong></h1>
    <div>
        <div>Description: <em>{{ product.description }}</em></div>
        <div>Price: {{ product.price }}</div>
        <div>Discount: {{ product.discount }}</div>
        <div>Archived: {{ product.archived }}</div>

        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}

        {% if product.images.all %}
            <h3>
                {% blocktranslate count img_count=product.images.all|length %}
                    There is only one image:
                    {% plural %}
                    There are {{ img_count }} images:
                {% endblocktranslate %}
            </h3>

            <div>
                {% for img in product.images.all %}
                    <div>
                        <img src="{{ img.image.url }}" alt="img.image.name">
                        <div>{{ img.description }}</div>
                    </div>

                {% endfor %}
            </div>
        {% else %}
            <br>
            <div>{% translate 'No images uploaded yet' %}</div>
        {% endif %}
    </div>
    <br><br>
    {% url 'shopapp:product_update' pk=product.pk as prod_update %}
    {% url 'shopapp:product_delete' pk=product.pk as prod_del %}
    {% url 'shopapp:products_list' as prod_list %}
    {% blocktranslate %}
        <div><a href="{{ prod_update }}">Update product</a></div>
        <br>
        <div><a href="{{ prod_del }}">Archive product</a></div>
        <br>
        <div>
            <a href="{{ prod_list }}"> Back to products list</a>
        </div>
        <br>
    {% endblocktranslate %}
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm Archive {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to Archive {{ object.name }}?</h1>

    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archive</button>
        </form>
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}">Back to product</a>
    </div>
    <br>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create new product:</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <br><br>
    <di>
        <a href="{% url 'shopapp:products_list' %}">Back to product list</a>
    </di>
    <br><br>

{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Product #{{ product.pk }}
{% endblock %}

{% block body %}
  <h1>Product <strong>{{ product.name }}</strong></h1>
  <div>
    <div>Description: <em>{{ product.description }}</em></div>
    <div>Price: {{ product.price }}</div>
    <div>Discount: {{ product.discount }}</div>
    <div>Archived: {{ product.archived }}</div>
  </div>
  <div>
    <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>
  </div>
  <div>
    <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Archive product</a>
  </div>
  <div>
    <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% translate 'Products list' %}
{% endblock %}

{% block body %}
    <h1>{% translate 'Products' %}:</h1>
    {% if products %}
        <div>
            {% blocktranslate count products_count=products|length %}
                There is only one product
                {% plural %}
                There are {{ products_count }} products
            {% endblocktranslate %}
        </div>

        <div>
            {% for product in products %}
                <div>
                    <p><a href="{% url 'shopapp:product_details' pk=product.pk %}"
                    >{% translate 'Name' context 'product name' %}: {{ product.name }}</a></p>
                    <p>Price: {{ product.price }}</p>
                    {% translate 'no discount' as no_discount %}
                    <p>Discount: {% firstof product.discount no_discount %}</p>
                    <p>Created by: {% firstof product.created_by.first_name product.created_by.username %}</p>
                    {% if product.preview %}
                        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% else %}
        {% url 'shopapp:product_create' as create_product_url %}
        {% blocktranslate %}
            <h3>No products yet</h3>
            <a href="{{ create_product_url }}">Create product</a>
        {% endblocktranslate %}
    {% endif %}
    <br><br>
    <div>
        {% if perms.shopapp.product_create %}
            <a href="{% url 'shopapp:product_create' %}"> {% translate 'Create product' %}</a>
        {% endif %}
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:index' %}"> Go back to shop-index</a>
    </div>
    <br>
{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}
{% block object-tools-items %}
    {% load admin_urls %}

    <li>
        <a href="{% url 'admin:import_products_csv' %}" class="addlink">
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    Shop Index
{% endblock %}

{% block body %}
    <h1>Hello from Shop index!</h1>
    <div>
        Time running: {{ time_running }}
    </div>
    <div>
        <ul>
            {% for name, price in products %}
                <li>{{ name|capfirst }} ({{ name|length }}) for ${{ price }}</li>
                {% if name|length_is:'7' %}
                    <span>Lucky product!</span>
                {% endif %}
            {% empty %}
                No products here
            {% endfor %}
        </ul>
    </div>
    <div>
        <strong>
            You have {{ items }} class{{ items|pluralize:"es" }}<br>
            You have {{ items }} cherr{{ items|pluralize:"y,ies" }}
        </strong>
    </div>

    {% cache 100 lorem %}
        <div>
            {% lorem 3 p random %}
        </div>
    {% endcache %}

    <br><br>
    <div>
        <a href="{% url 'shopapp:products_list' %}">Go to product list</a>
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">Go to order list</a>
    </div>
    <br>
{% endblock %}

mysite/shopapp/templates/shopapp/user_order.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    {{ owner }}'s Orders
{% endblock %}

{% block body %}
    <br>
    {% if orders %}
        <h3>{{ owner }} has following orders:</h3>
        {% with total=owner.pk %}
            {% cache 30 owner_orders total %}
                {% for order in orders %}
                    <div>
                        <p>Order #{{ order.pk }}:</p>
                        <p>
                            Delivery address: {{ order.delivery_address }}
                        </p>
                        <p>Promo code:
                            <cod>{{ order.promo_code }}</cod>
                        </p>
                        <div>
                            Products in order:
                            <ul>
                                {% for product in order.products.all %}
                                    <li>{{ product.name }} for ${{ product.price }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        <br>
                    </div>
                {% endfor %}
                <a href="{% url 'shopapp:user_orders_list_export' owner.pk %}">Export Orders</a>
            {% endcache %}
        {% endwith %}
    {% else %}
        <h4>{{ owner }} made no orders yet</h4>
    {% endif %}


{% endblock %}