mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

# from .views import login_view, logout_view
from myauth.views import get_cookie_view, set_cookie_view, set_session_view, get_session_view, MyLogoutView, \
    AboutMeView, RegisterView, FooBarView, ChangeAvatarView, ProfileListView, ProfileDetailsView, \
    ChangeAvatarIsStaffView, HelloView

app_name = 'myauth'

urlpatterns = [
    path('login/',
         LoginView.as_view(
             template_name='myauth/login.html',
             redirect_authenticated_user=True),
         name='login'),
    path('hello/', HelloView.as_view(), name='hello'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('cookie/get/', get_cookie_view, name='cookie-get'),
    path('cookie/set/', set_cookie_view, name='cookie-set'),
    path('session/get/', get_session_view, name='session-get'),
    path('session/set/', set_session_view, name='session-set'),

    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path('register/', RegisterView.as_view(), name='register'),
    path('change-avatar/<int:pk>/', ChangeAvatarView.as_view(), name='change-avatar'),

    path("profiles-list/", ProfileListView.as_view(), name="profiles-list"),
    path("profiles-details/<int:pk>/", ProfileDetailsView.as_view(), name="profile-details"),
    path('profiles-details/<int:pk>/change-avatar-staff', ChangeAvatarIsStaffView.as_view(),
         name='change-avatar-staff'),

    path('foo-bar/', FooBarView.as_view(), name='foo-bar')
    # path('login/', login_view, name='login'),
    # path('logout/', logout_view, name='logout'),

]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from .sitemaps import sitemaps

urlpatterns = []

urlpatterns += i18n_patterns(
    path('', include('mainpage.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('shop/', include('shopapp.urls')),
    path('accounts/', include('myauth.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swager/', SpectacularSwaggerView.as_view(url_name='schema'), name='swager'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('blog/', include('BlogApp.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    )

)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def profile_avatar_directory_path(instance: "Profile", filename: str) -> str:
    return 'profiles/profile_{pk}/avatar/{filename}'.format(
        pk=instance.pk,
        filename=filename,
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(blank=True, null=True, upload_to=profile_avatar_directory_path)

    def __str__(self) -> str:
        return f"Profile ( pk= {self.pk}, name= {self.user.username!r})"

mysite/myauth/forms.py
from django import forms
from django.forms import ModelForm

from .models import Profile

class ProfileUpdateForm(forms.ModelForm):
    first_name = forms.CharField(max_length=32)
    last_name = forms.CharField(max_length=32)
    class Meta:
        model = Profile
        fields = ['avatar']

mysite/myauth/views.py
from random import random

from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DetailView
from django.utils.translation import gettext_lazy as _, ngettext

from myauth.models import Profile


class HelloView(View):
    welcome_message = _('Hello World! text')

    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET.get('items') or 0
        items = int(items_str)
        products_line = ngettext(
            "one product",
            "{count} products",
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>"
            f"\n<h2>{products_line}</h2>"
        )


class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy('myauth:about-me')

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response


def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('/admin/')

        return render(request, 'myauth/login.html')

    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/admin/')

    return render(request, 'myauth/login.html', {"error": 'invalid login credentials'})


def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect(reverse('myauth:login'))


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('myauth:login')


@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('Cookie set')
    response.set_cookie('fizz', 'buzz', max_age=3600)
    return response

@cache_page(60 * 2)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get('fizz', 'default value')
    return HttpResponse(f'Cookie value: {value!r} + {random()}')


@permission_required('myauth.view_profile', raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session['foobar'] = 'spameggs'
    return HttpResponse('Session set!')


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get('foobar', 'default')
    return HttpResponse(f'Session value: {value!r}')


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({'foo': 'bar', 'spam': 'eggs'})


class ChangeAvatarView(UpdateView):
    model = Profile
    fields = "bio", "avatar"
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'myauth:about-me'
        )


class ProfileListView(ListView):
    template_name = 'myauth/profiles-list.html'
    context_object_name = "profiles"

    def get_queryset(self):
        return User.objects.all()


class ProfileDetailsView(DetailView):
    template_name = 'myauth/profile-details.html'
    context_object_name = "profile"
    model = Profile


class ChangeAvatarIsStaffView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        if self.request.user.is_staff:
            return True

    model = Profile
    fields = ("avatar",)
    template_name = 'myauth/avatar_update_form.html'

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse(
            'myauth:profile-details', kwargs={'pk': pk}
        )

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}
{% load cache %}

{% block title %}
    About me
{% endblock %}


{% block body %}
    <h1>User info </h1>
    <div>
    Products available: {% now 'u' %}
    </div>
    {% if user.is_authenticated %}
        {% cache 30 userinfo user.username %}
            <h2>Detail</h2>
            <p>Username: {{ user.username }}</p>
            <p>First name: {{ user.first_name }}</p>
            <p>Last name: {{ user.last_name }}</p>
            <p>Email: {{ user.email }}</p>
            <p>Bio: {{ user.profile.bio }}</p>
            <br>
            {% if user.profile.avatar %}
                <img src="{{ user.profile.avatar.url }}" alt="{{ user.username }}">
                <br><br>
            {% else %}
                <p>Avatar: No avatar uploaded yet</p>
            {% endif %}


            <a href="{% url 'myauth:change-avatar' user.id %}">Update Avatar/Bio</a>
            <br><br>
        {% endcache %}

    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/avatar_update_form.html
{% extends 'myauth/base.html' %}

{% block title %}
    Update profile
{% endblock %}

{% block body %}
    <h1>Update avatar of {{ profile.user.username }}:</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <br><br>
    <di>
        <a href="{% url 'myauth:profile-details' profile.id %}">Back to my profile</a>
    </di>
    <br><br>

{% endblock %}

mysite/myauth/templates/myauth/base.html
{% extends 'mainpage/index.html' %}

{% block index-body %}

    {% block body %}

    {% endblock %}

{% endblock %}

mysite/myauth/templates/myauth/login-handmade.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {% if error %}
        <p style="color: red">{{ error }}</p>
        {% endif %} 
        <p>
            <lable id="username">Username:</lable>
            <input type="text" id="username" name="username" required>
        </p>
        <p>
            <lable id="password">Password:</lable>
            <input type="password" id="password" name="password" required>
        </p>

        <button type="submit">Login</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Login</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/profile-details.html
{% extends 'myauth/base.html' %}

{% block title %}
    About me
{% endblock %}


{% block body %}
    <h1>User info </h1>

        <h2>Detail</h2>
        <p>Username: {{ profile.user.username }}</p>
        <p>First name: {{ profile.user.first_name }}</p>
        <p>Last name: {{ profile.user.last_name }}</p>
        <p>Email: {{ profile.user.email }}</p>
        <p>Bio: {{ profile.bio }}</p>
        <br>
        {% if profile.avatar %}
            <img src="{{ profile.avatar.url }}" alt="{{ profile.user.username }}">
            <br><br>
        {% else %}
            <p>Avatar: No avatar uploaded yet</p>
        {% endif %}
        <br><br>
    {% if user.is_staff %}
                <a href="{% url 'myauth:change-avatar-staff' profile.id %}">Update Avatar</a>
        <br><br>
    {% endif %}

    <p><a href="{% url 'myauth:profiles-list' %}">Back</a></p>

{% endblock %}

mysite/myauth/templates/myauth/profile_update_form.html
{% extends 'myauth/base.html' %}

{% block title %}
    Update profile
{% endblock %}

{% block body %}
    <h1>Update profile:</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <br><br>
    <di>
        <a href="{% url 'myauth:about-me' %}">Back to my profile</a>
    </di>
    <br><br>

{% endblock %}

mysite/myauth/templates/myauth/profiles-list.html
{% extends 'myauth/base.html' %}

{% block title %}
    Products list
{% endblock %}

{% block body %}
    <h1>Profiles:</h1>
    {% if profiles %}
        <di>
            {% for profile in profiles %}
                <div>
                    <p>{{ forloop.counter }} <a
                            href="{% url 'myauth:profile-details' pk=profile.id %}">Name: {{ profile.username }}</a>
                    </p>
                </div>
            {% endfor %}

        </di>
    {% else %}
        <h3>No profiles yet</h3>
    {% endif %}
    <br><br>
    <div>
        <a href="{% url 'myauth:register' %}"> Create a new profile</a>
    </div>
    <br>

{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value="Register">
    </form>

    <br>
    <input type=button value="Back" onClick="javascript:history.go(-1);">
    <br>
{% endblock %}